import NARAppBar from '@/components/AppBar';
import { Box } from '@mui/material';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ padding: 0, margin: 0 }}>
        <NARAppBar />
        <Box sx={{ pt: 3 }}>{children}</Box>
      </body>
    </html>
  );
}
